---
title: "Results"
author: "Matt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(astsa)
library(sf)
library(reshape2)
library(gridExtra)
library(transformr)
# library(ape)
sf_use_s2(FALSE)
source("../../../utils/R/utils.R")
install()
library(inlabru)

# helper functions - project wide
source("./helpers.R")
```

## load the projections - using best model

```{r}
p126 = decache("ssp126")
p245 = decache("ssp245")
p585 = decache("ssp585")
```

## show the trends in set regions - with region overlay
```{r}

# choose some regions to display
displayRegs = c(14,13,6,23)
printed = 
flip = c(13,23)

plts = list()

for(i in 1:nrow(regions)){
  # skip unless we chose this region to display - all is too many for paper
  if(! i %in% displayRegs){
    next
  }
  # look up the best model and region combo one by one
  model = "sarima+AR"    #bestpredModel[i,]$best
  reg = regions$GID_1[i] #bestpredModel[i,]$Region
  regname = regionNameLookup(reg,locs)
  
  # get the data for the given region and best model type
  pred126 = filter(p126, gid==reg)
  pred245 = filter(p245, gid==reg)
  pred585 = filter(p585, gid==reg)

  # plot the general trend in each case
  plotTitle = paste("Region", regname,"-",model,"model")
  regtrend = plot(ggplot() +
        #geom_line(aes(x=ym, y=cases, colour="126"), data=pred126, alpha=0.25) + 
        geom_smooth(aes(x=ym, y=cases, colour="126"), data=pred126, alpha=0.5, se=T) + 
         
         
        #geom_line(aes(x=ym, y=cases, colour="245"), data=pred245, alpha=0.25) +
        geom_smooth(aes(x=ym, y=cases, colour="245"), data=pred245, alpha=0.5, se=T) +
         
        #geom_line(aes(x=ym, y=cases, colour="585"), data=pred585, alpha=0.25) + 
        geom_smooth(aes(x=ym, y=cases, colour="585"), data=pred585, alpha=0.5, se=T) + 
          
        ggtitle(plotTitle) +
        labs(colour="Scenario") +
        theme_bw())
  regtrend = dateAxis(pred126, regtrend, each=10, format="%Y")
  # corner map
  regmap = plotRegion(regions, regId=i, idCol="gid") + ggtitle("") + 
    theme(axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          panel.background = element_rect(fill="transparent"),
          plot.background = element_rect(fill="transparent", color = NA))
    
  regplt = gridExtra::grid.arrange(regtrend, regmap, padding = unit(1),
                                   layout_matrix=rbind(
                                      c(2,2,2,1,1,1,1),
                                      c(2,2,2,1,1,1,1),
                                      c(2,2,2,1,1,1,1),
                                      c(1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1)))
  if(i %in% flip){
    regplt = gridExtra::grid.arrange(regtrend, regmap, padding = unit(1),
                                   layout_matrix=rbind(
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(2,2,2,2,2,2,2,1,1,1,1,1,1,1),
                                      c(2,2,2,2,2,2,2,1,1,1,1,1,1,1),
                                      c(2,2,2,2,2,2,2,1,1,1,1,1,1,1),
                                      c(2,2,2,2,2,2,2,1,1,1,1,1,1,1),
                                      c(2,2,2,2,2,2,2,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                                      c(1,1,1,1,1,1,1,1,1,1,1,1,1,1)))
  }
  
  plot(regplt)
  saveimg(regplt, paste("proj-",regname,sep=""))
}
```



## Disease mapping: show the start-end difference maps per scenario

```{r}

diffs=colmetric(locs, "GID_1", metric=function(reg, row){
  model = "sarima+AR" 
  regname = regionNameLookup(reg,locs)
  
  pred126 = filter(p126, gid==reg)
  pred245 = filter(p245, gid==reg)
  pred585 = filter(p585, gid==reg)
  
  # difference in first and last year mean cases
  diff126 = mean(pred126[pred126$year==max(pred126$year),]$cases) - 
            mean(pred126[pred126$year==min(pred126$year),]$cases)
  
  diff245 = mean(pred245[pred245$year==max(pred245$year),]$cases) - 
            mean(pred245[pred245$year==min(pred245$year),]$cases)
  
  diff585 = mean(pred585[pred585$year==max(pred585$year),]$cases) - 
            mean(pred585[pred585$year==min(pred585$year),]$cases)
  
  vals = list("d126"=diff126,
               "d245"=diff245,
               "d585"=diff585)
  return(vals)
})


regionProj = bind_cols(regions, bind_rows(diffs))

# per scenario average yearly change in snakebites
lowest = min(st_drop_geometry(select(regionProj, d126, d245, d585)))
highest = max(st_drop_geometry(select(regionProj, d126, d245, d585)))

region126plot = ggplot(regionProj) + 
  geom_sf(aes(fill=d126)) +
  scale_fill_gradient2(midpoint=0, low="limegreen", mid="white", high="red3", 
                       limits=c(lowest,highest)) +
  ggtitle("Scenario 126, projected 100 year change in mean annual snakebites") + 
  labs("fill"="Change") +
  theme_bw()
region126plot
saveimg(region126plot)

region245plot = ggplot(regionProj) + 
  geom_sf(aes(fill=d245)) +
  scale_fill_gradient2(midpoint=0, low="limegreen", mid="white", high="red3", 
                       limits=c(lowest,highest)) +
  ggtitle("Scenario 245, projected 100 year change in mean annual snakebites") + 
  labs("fill"="Change") +
  theme_bw()
region245plot
saveimg(region245plot)

region585plot = ggplot(regionProj) + 
  geom_sf(aes(fill=d585)) +
  scale_fill_gradient2(midpoint=0, low="limegreen", mid="white", high="red3", 
                       limits=c(lowest,highest)) +
  ggtitle("Scenario 585, projected 100 year change in mean annual snakebites") + 
  labs("fill"="Change") +
  theme_bw()
region585plot
saveimg(region585plot)

```











